import type { AnySourceConfig } from "@/lib/types";

const SOURCES: AnySourceConfig[] = [
  {
    id: "hn-top",
    type: "hackernews",
    displayName: "Hacker News",
    enabled: true,
    endpoint: "topstories",
    limit: 30,
  },
  {
    id: "tldr-tech",
    type: "rss",
    displayName: "TLDR Tech",
    enabled: true,
    url: "https://tldr.tech/api/rss/tech",
    limit: 20,
  },
  {
    id: "the-verge",
    type: "rss",
    displayName: "The Verge",
    enabled: true,
    url: "https://www.theverge.com/rss/index.xml",
    limit: 20,
  },
  {
    id: "lobsters",
    type: "rss",
    displayName: "Lobste.rs",
    enabled: true,
    url: "https://lobste.rs/rss",
    limit: 25,
  },
  {
    id: "ars-technica",
    type: "rss",
    displayName: "Ars Technica",
    enabled: true,
    url: "https://feeds.arstechnica.com/arstechnica/index",
    limit: 20,
  },
  {
    id: "jeff-geerling",
    type: "rss",
    displayName: "Jeff Geerling",
    enabled: true,
    url: "https://www.jeffgeerling.com/blog.xml",
    limit: 15,
  },
  {
    id: "xkcd",
    type: "rss",
    displayName: "xkcd",
    enabled: true,
    url: "https://xkcd.com/rss.xml",
    limit: 10,
  },
  {
    id: "the-new-stack",
    type: "rss",
    displayName: "The New Stack",
    enabled: true,
    url: "https://thenewstack.io/blog/feed/",
    limit: 20,
  },
  {
    id: "bleeping-computer",
    type: "rss",
    displayName: "Bleeping Computer",
    enabled: true,
    url: "https://www.bleepingcomputer.com/feed/",
    limit: 20,
  },
  {
    id: "cnx-software",
    type: "rss",
    displayName: "CNX Software",
    enabled: true,
    url: "https://www.cnx-software.com/feed/",
    limit: 15,
  },
  {
    id: "linux-gizmos",
    type: "rss",
    displayName: "Linux Gizmos",
    enabled: true,
    url: "https://linuxgizmos.com/feed/",
    limit: 15,
  },
];

export default SOURCES;
