export const KNOWN_TAGS = [
  "AI/ML",
  "Web Dev",
  "Security",
  "DevOps",
  "Science",
  "Business",
  "Open Source",
  "Other",
] as const;

export type KnownTag = (typeof KNOWN_TAGS)[number];

// Maps tag → keywords to match in lowercased title
export const TAG_RULES: Record<KnownTag, string[]> = {
  "AI/ML": [
    "ai",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "llm",
    "gpt",
    "claude",
    "gemini",
    "openai",
    "anthropic",
    "transformer",
    "diffusion",
    "stable diffusion",
    "midjourney",
    "chatgpt",
    "copilot",
    "nlp",
    "computer vision",
    "reinforcement learning",
    "hugging face",
    "pytorch",
    "tensorflow",
    "model",
    "inference",
    "fine-tun",
    "rag",
    "embedding",
    "vector",
  ],
  "Web Dev": [
    "javascript",
    "typescript",
    "react",
    "vue",
    "angular",
    "svelte",
    "next.js",
    "nextjs",
    "node.js",
    "nodejs",
    "css",
    "html",
    "frontend",
    "backend",
    "api",
    "rest",
    "graphql",
    "webpack",
    "vite",
    "bun",
    "deno",
    "browser",
    "web assembly",
    "wasm",
    "tailwind",
    "vercel",
    "netlify",
  ],
  Security: [
    "security",
    "vulnerability",
    "exploit",
    "hack",
    "breach",
    "malware",
    "ransomware",
    "phishing",
    "zero-day",
    "cve",
    "xss",
    "sql injection",
    "authentication",
    "encryption",
    "privacy",
    "cyber",
    "password",
    "2fa",
    "oauth",
    "jwt",
    "penetration",
    "pentest",
  ],
  DevOps: [
    "docker",
    "kubernetes",
    "k8s",
    "ci/cd",
    "devops",
    "terraform",
    "ansible",
    "jenkins",
    "github actions",
    "cloud",
    "aws",
    "gcp",
    "azure",
    "microservices",
    "container",
    "serverless",
    "monitoring",
    "observability",
    "logging",
    "deployment",
    "infrastructure",
    "linux",
  ],
  Science: [
    "science",
    "research",
    "study",
    "physics",
    "biology",
    "chemistry",
    "space",
    "nasa",
    "climate",
    "genome",
    "dna",
    "quantum",
    "neuroscience",
    "psychology",
    "mathematics",
    "statistics",
    "experiment",
    "discovery",
    "paper",
    "journal",
    "arxiv",
  ],
  Business: [
    "startup",
    "funding",
    "ipo",
    "acquisition",
    "layoff",
    "hiring",
    "revenue",
    "profit",
    "market",
    "stock",
    "valuation",
    "venture",
    "investor",
    "ceo",
    "enterprise",
    "saas",
    "product",
    "launch",
    "announced",
    "raises",
  ],
  "Open Source": [
    "open source",
    "open-source",
    "github",
    "gitlab",
    "license",
    "mit license",
    "apache license",
    "gpl",
    "fork",
    "pull request",
    "contributor",
    "maintainer",
    "repository",
    "release",
    "v1.",
    "v2.",
    "v3.",
  ],
  Other: [],
};
